[workspace]
members = [
    "kernel",
    "bootloader",
    "projects/apps/fatboot",
    "projects/apps/hello",
    "projects/libs/abi",
    "projects/libs/user",
    "projects/libs/runtime",
    "projects/libs/runtime-macros",
]
default-members = ["kernel"]
resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 2
