[workspace]
members = [
    "kernel",
    "bootloader",
    "projects/apps/userboot",
    "projects/apps/init",
    "projects/apps/console",
    "projects/apps/hello",
    "projects/apps/block-server",
    "projects/apps/fs-server",
    "projects/apps/appmgr",
    "projects/apps/mysh",
    "projects/libs/abi",
    "projects/libs/alloc",
    "projects/libs/elf",
    "projects/libs/newc",
    "projects/libs/protocol",
    "projects/libs/server",
    "projects/libs/initcfg",
    "projects/libs/user",
    "projects/libs/runtime",
    "projects/libs/runtime-macros",
]
default-members = ["kernel"]
resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 2
