#pragma once
#define CONFIG_ARCH_ARM 1
#define CONFIG_ARCH_AARCH64 1
#define CONFIG_ARCH_ARM_V8A 1
#define CONFIG_WORD_SIZE 64
#define CONFIG_MAX_NUM_NODES 1
#define CONFIG_PLAT_QEMU_ARM_VIRT 1
#define CONFIG_ARM_CORTEX_A72 1
