[package]
name = "fatboot"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fatboot"
path = "src/main.rs"
test = false
bench = false

[dependencies]
rstiny = { path = "../../libs/user" }
rstiny-runtime = { path = "../../libs/runtime" }
rs_fdtree = { path = "../../../drivers/platform/rs-fdtree" }
