[package]
name = "init"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "init"
path = "src/main.rs"
test = false
bench = false

[dependencies]
rstiny = { path = "../../libs/user" }
rstiny-runtime = { path = "../../libs/runtime" }
rstiny-server = { path = "../../libs/server" }
rstiny-protocol = { path = "../../libs/protocol" }
rstiny-newc = { path = "../../libs/newc" }
rstiny-initcfg = { path = "../../libs/initcfg" }
