[package]
name = "fs_server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fs_server"
path = "src/main.rs"
test = false
bench = false

[dependencies]
rstiny = { path = "../../libs/user" }
rstiny-runtime = { path = "../../libs/runtime" }
rstiny-server = { path = "../../libs/server" }
rstiny-protocol = { path = "../../libs/protocol" }
hadris-fat = { version = "2.4.0", default-features = false, features = ["read", "sync", "alloc"] }
embedded-io = { version = "0.7", default-features = false }
