#!/usr/bin/env python3
"""Validate configs/system.toml and generate the runtime manifests.

system.toml is the single build-time source of truth (docs/service-manager.md):
service definitions, per-task behavior flags (heap, ready) and the boot-image
profiles. This script

  1. validates it (dependency closure and acyclicity, per-profile budget sum
     against init's grant, device/dependency/IRQ arity, budget encoding),
  2. generates the `*.cfg` files init and appmgr parse at runtime, and
  3. with --check-elfs, cross-checks the heap flag against the built ELFs
     (a heap = false task must not reference rstiny-alloc).

`--check` regenerates into a scratch directory and fails when the committed
configs drifted; `make manifest` regenerates them in place.
"""
import argparse
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED_HEADER = "# Generated by tools/build_manifest.py from configs/system.toml - do not edit."
DEFAULTS = {"restart": "on-failure", "max_restarts": 5, "window_ms": 60000,
            "backoff_ms": 100, "heap": True, "ready": "entry"}
MAX_DEPS = 3        # init SpawnInfo::MAX_DEPS
MAX_DEVICES = 4     # init SpawnInfo::MAX_DEVICES
MAX_IRQS = 2        # init SpawnInfo::MAX_DEVICE_IRQS (virtio devices only)
ELF_HEAP_SYMBOL = b"rstiny_alloc"


def fail(message):
    print(f"system.toml: {message}", file=sys.stderr)
    sys.exit(1)


def parse_budget(text):
    """`1M` style budgets to bytes, as the initcfg parser accepts them."""
    digits, suffix = text[:-1:], text[-1]
    if suffix not in "KM" or not digits.isdigit() or not (1 <= len(digits) <= 9):
        fail(f"budget {text!r}: expected <digits><K|M>, 1..9 digits")
    value = int(digits) * (1024 if suffix == "K" else 1024 * 1024)
    if value.bit_length() < 12 or value.bit_length() > 30:
        fail(f"budget {text!r}: must encode as 12..30 bits (4 KiB..1 GiB)")
    return value


def value_budget(bits):
    return 1 << bits


def emit_service(name, spec, profile_overrides, system_defaults):
    """One `service { }` block, initcfg-parser compatible."""
    merged = dict(system_defaults)
    merged.update({key: value for key, value in spec.items() if value is not None})
    merged.update(profile_overrides or {})
    lines = []
    if merged.get("notes"):
        lines += [f"# {note}" for note in merged["notes"].strip().splitlines()]
    if merged.get("ready", "entry") != "entry":
        lines.append(f"# ready: {merged['ready']}")
    lines.append(f"service {name} {{")
    lines.append(f'    elf = "{merged["elf"]}"')
    depends = merged.get("depends", [])
    if depends:
        lines.append("    depends = " + " ".join(depends))
    for device in merged.get("devices", []):
        lines.append(f'    device = "{device}"')
    lines.append(f'    restart = {merged.get("restart", DEFAULTS["restart"])}')
    if merged.get("max_restarts", DEFAULTS["max_restarts"]) != DEFAULTS["max_restarts"]:
        lines.append(f'    max_restarts = {merged["max_restarts"]}')
    if merged.get("window_ms", DEFAULTS["window_ms"]) != DEFAULTS["window_ms"]:
        lines.append(f'    window_ms = {merged["window_ms"]}')
    if merged.get("backoff_ms", DEFAULTS["backoff_ms"]) != DEFAULTS["backoff_ms"]:
        lines.append(f'    backoff_ms = {merged["backoff_ms"]}')
    if merged.get("budget"):
        lines.append(f'    budget = "{merged["budget"]}"')
    lines.append("}")
    return "\n".join(lines), merged


def generate_profile(kind, entries, specs, defaults, overrides_for):
    out = [f"# {entries['output']} - generated from configs/system.toml "
           f"(docs/service-manager.md) - do not edit.", ""]
    if entries.get("notes"):
        out += [f"# {note}" for note in entries["notes"].strip().splitlines()]
        out.append("")
    if kind == "services":
        blocks = []
        for name in entries["services"]:
            if name not in specs:
                fail(f"profile {entries.get('output')}: service {name!r} is not defined")
            block, _ = emit_service(name, specs[name], overrides_for(name), defaults)
            blocks.append(block)
        out.append("\n\n".join(blocks))
    else:
        blocks = []
        for name in entries["apps"]:
            if name not in specs:
                fail(f"profile {entries.get('output')}: app {name!r} is not defined")
            block, _ = emit_service(name, specs[name], None, defaults)
            blocks.append(block)
        out.append("\n\n".join(blocks))
    return "\n".join(out) + "\n"


def validate(services, apps, profiles, init_budget_bytes, defaults):
    for name, spec in services.items():
        merged = dict(defaults)
        merged.update({k: v for k, v in spec.items() if v is not None})
        for dependency in merged.get("depends", []):
            if dependency not in services:
                fail(f"service {name}: depends on undefined service {dependency!r}")
        if len(merged.get("depends", [])) > MAX_DEPS:
            fail(f"service {name}: more than {MAX_DEPS} dependencies")
        devices = merged.get("devices", [])
        if len(devices) > MAX_DEVICES:
            fail(f"service {name}: more than {MAX_DEVICES} devices")
        irqs = sum(1 for d in devices if d.startswith("virtio"))
        if irqs > MAX_IRQS:
            fail(f"service {name}: {irqs} virtio devices exceed the {MAX_IRQS} IRQ grants")
        if "budget" in merged:
            parse_budget(merged["budget"])
    for pname, profile in profiles.items():
        kind = "services" if "services" in profile else "apps"
        members = profile.get(kind, [])
        total = 0
        for name in members:
            if name not in services and name not in apps:
                fail(f"profile {pname}: {name!r} is not defined")
            source = services if name in services else apps
            spec = dict(defaults)
            spec.update({k: v for k, v in source[name].items() if v is not None})
            spec.update(profile.get("overrides", {}).get(name, {}))
            total += parse_budget(spec["budget"]) if "budget" in spec else 1024 * 1024
        if profile.get("services") and total > init_budget_bytes:
            fail(f"profile {pname}: service budgets sum to {total >> 20} MiB, "
                 f"above init's {init_budget_bytes >> 20} MiB grant")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the generated configs drifted")
    parser.add_argument("--check-elfs", action="store_true",
                        help="verify heap = false against the built ELFs")
    parser.add_argument("--mode", default="release", choices=("debug", "release"))
    parser.add_argument("--generate", action="store_true",
                        help="write the generated configs over configs/")
    options = parser.parse_args()

    source = ROOT / "configs" / "system.toml"
    manifest = tomllib.loads(source.read_text())
    defaults = dict(DEFAULTS)
    defaults.update(manifest.get("defaults", {}))
    services = manifest.get("services", {})
    apps = manifest.get("apps", {})
    profiles = manifest.get("profiles", {})
    init_budget = parse_budget(manifest.get("system", {}).get("init_budget", "16M"))
    budget_default_bits = None  # initcfg parser default applies when unset

    validate(services, apps, profiles, init_budget, defaults)

    outputs = {}
    for pname, profile in profiles.items():
        kind = "services" if "services" in profile else "apps"
        output = profile.get("output")
        if not output:
            fail(f"profile {pname}: missing output")
        overrides = profile.get("overrides", {})
        text = generate_profile(kind, profile, services if kind == "services" else apps,
                                defaults, lambda name: overrides.get(name))
        outputs[output] = text

    if options.generate or options.check:
        destination = ROOT / "configs"
        for name, text in outputs.items():
            target = destination / name
            if options.check:
                if not target.exists() or target.read_text() != text:
                    fail(f"configs/{name} is stale: run `make manifest`")
            else:
                target.write_text(text)
                print(f"generated configs/{name}")
    else:
        for name, text in outputs.items():
            print(f"--- configs/{name} ---")
            print(text)

    if options.check_elfs:
        for name, spec in services.items():
            merged = dict(defaults)
            merged.update({k: v for k, v in spec.items() if v is not None})
            if merged.get("heap", True):
                continue
            elf = ROOT / "target" / "apps" / options.mode / Path(merged["elf"])
            if not elf.exists():
                print(f"heap check: {merged['elf']} not built yet, skipped")
                continue
            symbols = subprocess.run(["rust-nm", str(elf)], capture_output=True)
            if ELF_HEAP_SYMBOL in symbols.stdout or ELF_HEAP_SYMBOL in symbols.stderr:
                fail(f"{merged['elf']}: heap = false but the ELF references rstiny_alloc")
            print(f"heap check: {merged['elf']} clean")
        for name, spec in apps.items():
            merged = dict(defaults)
            merged.update({k: v for k, v in spec.items() if v is not None})
            if merged.get("heap", True):
                continue
            elf = ROOT / "target" / "apps" / options.mode / (merged["elf"] + ".elf")
            if elf.exists():
                symbols = subprocess.run(["rust-nm", str(elf)], capture_output=True)
                if ELF_HEAP_SYMBOL in symbols.stdout:
                    fail(f"{merged['elf']}: heap = false but the ELF references rstiny_alloc")
                print(f"heap check: {merged['elf']}.elf clean")

    return 0


if __name__ == "__main__":
    sys.exit(main())
