[package]
name = "rs_fdtree"
version = "0.2.0-rc2"
edition = "2024"
authors = ["KylinSoft Co., Ltd. <https://www.kylinos.cn/>"]
license = "Apache-2.0"
documentation = "https://gitee.com/openkylin/x-kernel"
description = "A pure-Rust #![no_std] crate for parsing Linux Flattened Devicetrees"
keywords = [
    "devicetree",
    "fdt",
    "dt",
    "linux",
]

[dependencies]
